logger:
  level: "debug"
  development: true

server:
  port: 8080

mongo:
  host: "mongo"
  port: 27017
  database: "catalog"
  replica-set: rs0
  migrations:
    enabled: true
    auto-migrate: true

kafka:
  brokers: "kafka:29092"
  schema-registry:
    url: "http://schema-registry:8081"
    auto-register-schemas: true

security:
  token:
    public-key: "eb6ebefd6a2b0a304d43c2ccca329aef0a1439d429dbe8ca9b6190622ce38341"

observability:
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  tracing:
    enabled: true
  metrics:
    enabled: false
